name: navicare
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+8

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

  # LiveKit for video calls
  livekit_client: ^2.5.4
  crypto: ^3.0.3
  dart_jsonwebtoken: ^3.3.1
  permission_handler: ^11.3.1

  # State Management
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1

  # Network & API
  dio: ^5.4.1
  google_fonts: ^6.2.1
  flutter_background: ^1.3.0+1
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.5.3
  retrofit: ^4.1.0
  audioplayers: ^6.5.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  http: ^1.4.0
  googleapis_auth: ^2.0.0
  flutter_dotenv: ^5.2.1
  overlay_support: ^2.1.0
  intl: ^0.19.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.2
  table_calendar: ^3.1.3
  file_picker: ^10.3.3

  flutter_localizations:
    sdk: flutter
  socket_io_client: ^3.1.2
  image_picker: ^1.2.0
  fl_chart: ^0.66.2
  photo_view: ^0.15.0
  flutter_callkit_incoming: ^3.0.0
  url_launcher: ^6.3.2
  pip_view: ^0.9.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  retrofit_generator: 9.2.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/sounds/
    - assets/animations/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
